config/routes.rb
Rails.application.routes.draw do
#  resources :users
  root :to => 'home#index'
  resources :user_sessions
  resources :clients, except: :show
  resources :requests
  match "login" => "user_sessions#new", :as => "login", via: [:get, :post]
  match "logout" => "user_sessions#destroy", :as => "logout", via: [:get, :post]
  get 'requests/:id/zip' => "requests#zip", :as => 'zip_create'

#  get '404', :to => 'application#page_not_found'
end

app/models/client.rb
class Client < ApplicationRecord
  resourcify
  belongs_to  :user
  has_many    :requests
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :destroy]
  before_action :set_clients, only: [:index, :edit]
  before_action :require_login

  def index

  end

  def new
    @client = Client.new
  end

  def create
    @client = current_user.clients.create(client_params)
    if @client.valid?
      flash[:success]='Клиент успешно сохранен!'
      redirect_to clients_path
    else
      flash[:error]='Ошибка при сохранении!'
      render 'new'
    end
  end

  def edit

  end

  def update
    @client.update_attributes(client_params)
    if @client.valid?
      flash[:success]='Клиент успешно изменен!'
      redirect_to clients_path
    else
      flash[:error]='Ошибка при сохранении!'
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  protected

  def set_client
    @client = Client.find(params[:id])
  end

  def set_clients
    if current_user.has_role? :agent
      @clients = current_user.clients
    elsif current_user.has_role? :partner
      @clients = Client.all
    end
  end

  def client_params
    params.require(:client).permit(:name, :inn, :kpp)
  end


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
.row
  .col-md-2
    = simple_form_for(@client, html: {class: 'form-horizontal'}) do |f|
      %p= f.input :name, as: :string, label: 'Название', hint: false, placeholder: 'ООО "Рога и копыта"'
      %p= f.input :inn, as: :integer, label: 'ИНН', hint: false, placeholder: '1234567890'
      %p= f.input :kpp, as: :integer, label: 'КПП', hint: false, placeholder: '1234567890'
      %p
        = f.submit "Сохранить", class: "btn btn-sm btn-success"
        = link_to "Назад", :back, class: "btn btn-sm btn-primary"

app/views/clients/edit.html.haml
.page-header
  %h1
    Изменить клиента
= render 'form'

app/views/clients/index.html.haml
.page-header
  %h1
    Клиенты
- if @clients.empty?
  %p
    Нет сохраненных клиентов.
    = link_to "Создать нового?", new_client_path
-else
  %p.text-right= link_to "Создать нового клиента", new_client_path
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Название
        %th
    - @clients.each do |client|
      %tr
        %td= client.id
        %td= client.name
        %td.text-right
          = link_to "Изменить", edit_client_path(client), class: "btn btn-sm btn-primary"
          = link_to "Удалить", client, class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Действительно хотите удалить?"}

app/views/clients/new.html.haml
.page-header
  %h1
    Новый клиент
= render 'form'