config/routes.rb
Rails.application.routes.draw do
#  resources :users
  root :to => 'home#index'
  resources :user_sessions
  resources :clients, except: :show
  resources :requests
  match "login" => "user_sessions#new", :as => "login", via: [:get, :post]
  match "logout" => "user_sessions#destroy", :as => "logout", via: [:get, :post]
  get 'requests/:id/zip' => "requests#zip", :as => 'zip_create'

#  get '404', :to => 'application#page_not_found'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      redirect_to controller: :requests, action: :index
    else
      login_page
    end
  end

  private
  def login_page
    render 'home/login'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h2= @user.name

app/views/home/login.html.haml
= form_tag user_sessions_path, :method => :post, class: 'form-signin' do
  %h2.form-signin-heading Авторизация
  = label_tag :inputEmail, 'E-Mail', class: 'sr-only'
  = email_field_tag 'email', nil, class: 'form-control', placeholder: 'Email адрес', required: true, autofocus: true
  = label_tag :inputPassword, 'Пароль', class: 'sr-only'
  = password_field_tag 'password', nil, class: 'form-control', placeholder: 'Пароль', required: true, autofocus: true
  %div.checkbox
    %label
      =check_box_tag 'remember_me', nil, true
      Запомнить
  =button_tag  'Войти', class: 'btn btn-lg btn-primary btn-block'
  %p= link_to 'Забыли пароль?', '#'