config/routes.rb
Rails.application.routes.draw do
#  resources :users
  root :to => 'home#index'
  resources :user_sessions
  resources :clients, except: :show
  resources :requests
  match "login" => "user_sessions#new", :as => "login", via: [:get, :post]
  match "logout" => "user_sessions#destroy", :as => "logout", via: [:get, :post]
  get 'requests/:id/zip' => "requests#zip", :as => 'zip_create'

#  get '404', :to => 'application#page_not_found'
end

app/models/request.rb
class Request < ApplicationRecord
  resourcify
  mount_uploader :file_application, RequestUploader
  mount_uploader :file_passports, RequestUploader
  mount_uploader :file_project, RequestUploader
  mount_uploader :file_consent, RequestUploader
  mount_uploader :file_balans, RequestUploader
  belongs_to :user
  belongs_to :client, inverse_of: :requests
  accepts_nested_attributes_for :client, reject_if: :all_blank

  before_create :set_status
  #validates :client_id, presence: { message: "Обязательно укажите клиента" }
  validates :date_end, :date_start, presence: {message: "Укажите дату"}
  validates :bg_type, presence: {message: "Укажите тип БГ"}
  validates :issue, presence: {message: "Укажите номер извещения"}, if: :bg_type?
  validates :bg_summ, presence: {message: "Укажите сумму"}
  #before_validation :check_client_fields

  protected

  def set_status
    self.status = "2" if self.status.blank?
  end

  def check_client_fields
    if self.client_id.blank?
      self.client_id=self.client.id
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :zip]
  before_action :set_requests, :set_clients, only: [:index, :create]
  before_action :require_login

  def index
  end

  def show
  end

  def new
    @request = Request.new
    @request.build_client
    if current_user.has_role? :agent
      @clients = current_user.clients
    elsif current_user.has_role? :partner
      @clients = Client.all
    end
  end

  def create
    rp = request_params
    if rp[:client_id].present?
      rp.delete(:client_attributes)
    end
    @request = current_user.requests.new(rp)
    if @request.save
      flash[:success]='Заявка создана'
      redirect_to requests_path
    else
      flash[:error]='Ошибка при сохранении!'
      render 'new'
    end
  end

  def edit
    if current_user.has_role? :agent
      @clients = current_user.clients
    elsif current_user.has_role? :partner
      @clients = Client.all
    end
  end

  def update
    @request.update_attributes(request_params)
    if @request.valid?
      flash[:success]='Заявка сохранена'
      redirect_to requests_path
    else
      flash[:error]='Ошибка при сохранении!'
      render 'edit'
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path
  end

  def zip
    require 'rubygems'
    require 'zip'
    require 'pathname'

    Zip.setup do |c|
      c.on_exists_proc = true
      c.continue_on_exists_proc = true
      c.unicode_names = true
      c.default_compression = Zlib::BEST_COMPRESSION
    end

    files = [@request.file_application.current_path, @request.file_passports.current_path, @request.file_project.current_path, @request.file_consent.current_path]
    zipfile_name = "#{Rails.root}/public/uploads/request/#{@request.id}/#{@request.id}.zip"

    Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
      files.each {
          |file_to_be_zipped|

        filename = File.basename(file_to_be_zipped)

        if filename == @request.file_application_identifier
          filename = "Заявление на предоставление БГ.#{File.extname(filename)}"
        elsif filename == @request.file_passports_identifier
          filename = "Паспорта.#{File.extname(filename)}"
        elsif filename == @request.file_project_identifier
          filename = "Проект контракта.#{File.extname(filename)}"
        elsif filename == @request.file_consent_identifier
          filename = "Согласия на запрос и предоставление информации.#{File.extname(filename)}"
        end

        puts "zipper: archiving #{file_to_be_zipped} as #{filename} into #{zipfile}"

        zipfile.add(filename, file_to_be_zipped)
      }
    end

    File.open(zipfile_name, 'r') do |f|
      send_data f.read,
                :filename => "#{@request.id} - #{Client.find(@request.client_id).name}.zip",
                :type => 'application/zip',
                :disposition => 'attachment',
                :streaming => 'true',
                :buffer_size => '4096'
    end
    File.delete(zipfile_name)
  end

  protected

  def set_request
    @request = Request.find(params[:id])
  end

  def set_requests
    if current_user.has_role? :agent
      @requests = current_user.requests
    elsif current_user.has_role? :partner
      @requests = Request.all
    end
  end

  def set_clients
    if current_user.has_role? :agent
      @clients = current_user.clients
    elsif current_user.has_role? :partner
      @clients = Client.all
    end
  end

  def request_params
    params.require(:request).permit(:client_id, :template, :bg_type, :issue, :bg_summ, :summ_currency, :immediately,
                                    :date_end, :prepayment, :comment, :file_application, :file_passports, :file_project,
                                    :file_consent, :file_balans, :date_start, :client_attributes => [:id, :user_id, :name, :inn, :kpp])
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
  def client(client_id)
    Client.find(client_id)
  end

  def user(user_id)
    User.find(user_id)
  end

  def bg_type(value)
    case value.to_s
      when '1' then
        "Коммерческая"
      when '0' then
        "Госзакупка"
    end
  end


  def yes_no(value)
    case value.to_s
      when 'true' then
        "Да"
      when 'false' then
        "Нет"
    end
  end


end

app/views/requests/_client_form.html.haml
.client_form
  = f.simple_fields_for :client do |c|
    = c.input :name, as: :string, label: 'Название', hint: false, placeholder: 'ООО "Рога и копыта"'
    = c.input :inn, as: :integer, label: 'ИНН', hint: false, placeholder: '1234567890'
    = c.input :kpp, as: :integer, label: 'КПП', hint: false, placeholder: '1234567890'
    = c.input :user_id, :as => :hidden, :input_html => { :value => "#{current_user.id}" }

app/views/requests/_form.html.haml
.row
  = simple_form_for(@request, html: {class: 'form-horizontal'}) do |f|
    = f.input :client_id, collection: @clients, as: :select, prompt: 'Создать нового', label: 'Укажите клиента:'
    - if @request.client_id.blank?
      = render 'client_form', f: f
    = f.input :template, as: :radio_buttons, collection: [['Да',true], ['Нет',false]], label: 'Шаблон заказчика:', :item_wrapper_class => 'radio-inline'
    = f.input :bg_type, as: :radio_buttons, collection: [['Коммерческая',1], ['Госзакупка',0]], label: 'Тип гарантии:', :item_wrapper_class => 'radio-inline'
    = f.input :issue, placeholder: 'Номер извещения/закупки', label: false
    .row
      .col-md-8
        = f.input :bg_summ, label: 'Сумма БГ:', placeholder: '1 350 000'
      .col-md-4
        = f.input :summ_currency, label: 'Валюта:', as: :select, collection: [["&#8381;".html_safe, 'rub'], ["&euro;".html_safe, 'eur'], ["&dollar;".html_safe, 'usd']], prompt: false
    = f.input :immediately, as: :radio_buttons, collection: [['Да',true], ['Нет',false]], label: 'Срок гарантии с момента выдачи:', :item_wrapper_class => 'radio-inline'
    = f.input :date_start, as: :string, :input_html => {:data => {:provide => 'datepicker', 'date-format' => 'dd.mm.yyyy', 'date-autoclose' => 'true'}}, placeholder: 'c', label: false
    = f.input :date_end, as: :string, :input_html => {:data => {:provide => 'datepicker', 'date-format' => 'dd.mm.yyyy', 'date-autoclose' => 'true'}}, placeholder: 'по', label: false
    = f.input :prepayment, as: :radio_buttons, collection: [['Да',true], ['Нет',false]], label: 'Аванс', :item_wrapper_class => 'radio-inline'
    = f.input :comment, as: :text, label: 'Комментарий', placeholder: 'Комментарий'
    .row
      .col-md-8
        %p Заявление на предоставление банковской гарантии
      .col-md-4
        = f.input :file_application, as: :file, label: false
    .row
      .col-md-8
        %p Паспорта всех Учредителей, Генерального директора и Главного бухгалтера
      .col-md-4
        = f.input :file_passports, as: :file, label: false
    .row
      .col-md-8
        %p Проект контракта
      .col-md-4
        = f.input :file_project, as: :file, label: false
    .row
      .col-md-8
        %p Согласия юридического и физического лиц на запрос и предоставление информации в Бюро Кредитных Историй для всех учредителей и директора, образец
      .col-md-4
        = f.input :file_consent, as: :file, label: false
    .row
      .col-md-8
        %p Баланс и отчет о финансовых результатах предприятия за последние 5 отчетных периодов.
      .col-md-4
        -#= f.input :file_balans, as: :file, label: false


    %p{align: "center"}
      = f.submit 'Сохранить', class: 'btn btn-md btn-success'
      = link_to 'Назад', :back, class: 'btn btn-md btn-primary'

app/views/requests/edit.html.haml
.page-header
  %h1
    Изменить заявку
= render 'form'

app/views/requests/index.html.haml
.page-header
  %h1
    Заявки
  - if @requests.empty?
    %p
      Нет ни одной заявки.
      = link_to "Создать новую?", new_request_path if current_user.has_role? :agent
  -else
    %p.text-right= link_to "Создать новую заявку", new_request_path if current_user.has_role? :agent
    %table.table.table-hover
      %thead
        %tr
          %th Код заявки
          %th Клиент (ИНН)
          - if current_user.has_role? :partner
            %th Агент
          %th Дата заявки
          %th Статус
          - if current_user.has_role? :partner
            %th Одобрено
          %th Срок БГ (дней)
          %th Размер обеспечения
          %th
      - @requests.each do |request|
        %tr
          %td= link_to request.id, request
          %td
            = client(request.client_id).name
            = "(#{client(request.client_id).inn})"
          - if current_user.has_role? :partner
            %td= user(request.user_id).name
          %td= request.created_at.strftime("%d.%m.%Y %H:%M:%S")
          %td= request_status(request.status)
          - if current_user.has_role? :partner
            %td.danger одобрено?
          %td= "по #{request.date_end.strftime('%d.%m.%Y')} (#{request.date_end.mjd - request.created_at.to_date.mjd})"
          %td
            = summ_delimeter(request.bg_summ)
            = currency(request.summ_currency)

          %td.text-right
            = link_to "Изменить", edit_request_path(request), class: "btn btn-sm btn-primary"
            = link_to "Удалить", request, class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Действительно хотите удалить?"}

app/views/requests/new.html.haml
.page-header
  %h1
    Новая заявка
= render 'form'

app/views/requests/show.html.haml
.page-header
  %h3
    = "Заявка ##{@request.id} от #{client(@request.client_id).name} (#{client(@request.client_id).inn})"
.row
  .col-sm-6
    %p
      %h3 Анкета:
    %p
      %b Шаблон заказчика:
      = yes_no(@request.template)
    %p
      %b Тип гарантии:
      = bg_type(@request.bg_type)
      - if @request.bg_type==0
        = "(<b>#{@request.issue}</b>)".html_safe
    %p
      %b Сумма БГ:
      = summ_delimeter(@request.bg_summ)
      = currency(@request.summ_currency)
    %p
      %b Срок гарантии с момента выдачи:
      = yes_no(@request.immediately)
    %p
      %b Срок действия:
      = "по #{@request.date_end.strftime('%d.%m.%Y')} (#{@request.date_end.mjd - @request.created_at.to_date.mjd} дней)"
    %p
      %b Аванс:
      = yes_no(@request.prepayment)
    %p
      %b Комментарий:
      = @request.comment
  .col-sm-6
    %p
      %h3
        Документы:
        - if @request.file_application? || @request.file_passports? || @request.file_project? || @request.file_consent?
          %small= link_to "(Скачать архивом)", zip_create_path(id: @request.id)
    %p
      %b Заявление на предоставление БГ:
      = link_to "Скачать", @request.file_application.url, :"download"=>"#{@request.id} Заявление на предоставление БГ" if @request.file_application?
    %p
      %b Паспорта:
      = link_to "Скачать", @request.file_passports.url, :"download"=>"#{@request.id} Паспорта" if @request.file_passports?
    %p
      %b Проект контракта:
      = link_to "Скачать", @request.file_project.url, :"download"=>"#{@request.id} Проект контракта" if @request.file_project?
    %p
      %b Согласия на запрос и предоставление информации:
      = link_to "Скачать", @request.file_consent.url, :"download"=>"#{@request.id} Согласия на запрос и предоставление информации" if @request.file_consent?
    %p
      %b Баланс и отчет о финансовых результатах: